/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/_chat";
import { Route as ChatIndexRouteImport } from "./routes/_chat.index";
import { Route as ChatSettingsRouteImport } from "./routes/_chat.settings";
import { Route as ChatThreadIdRouteImport } from "./routes/_chat.$threadId";
const ChatRoute = ChatRouteImport.update({
  id: "/_chat",
  getParentRoute: () => rootRouteImport,
});
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChatRoute,
});
const ChatSettingsRoute = ChatSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ChatRoute,
});
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: "/$threadId",
  path: "/$threadId",
  getParentRoute: () => ChatRoute,
});
const ChatRouteChildren = {
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatSettingsRoute: ChatSettingsRoute,
  ChatIndexRoute: ChatIndexRoute,
};
const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren);
const rootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
};
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes();
